### ISSUE TITLE
500 Error: Cannot find module 'handlebars' / Uncaught Error: Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by liamfd** [rendrjs/rendr-examples#19] opened 2015-05-10 13:43 UTC
Hey, I hope this is the appropriate place for this. I've been looking to convert a few of my personal projects from straight node/backbone to rendr, and I'm really excited about it. I've been having a few issues getting the examples to run though.

I'm not clear on why this is happening (I'm not very familiar with broswerify) but the example apps don't seem to be seeing the handlebars module. I'm guessing that the actual version of handlebars they're supposed to be using is in rendr-handlebars, but when I do a fresh `git clone` of the examples, cd into one of them and `npm install` everything seems to go well, but whenever I go to any of the pages I get a  `500 Error: Cannot find module 'handlebars'`.

I can get around it by simply doing an `npm install handlebars`, but this seems to be covering up the root issue, because when I then go to the page I've got an `Uncaught Error: Cannot find module 'handlebars'` in the console, which seems to be preventing it from running properly as every page is getting pulled down from the server (presumably because the Backbone app isn't actually running.)

I've got a `compiledTemplates.js` file, so the grunt handlebars stuff seems to be working fine.
I'm guessing this is just something I'm doing wrong, but I don't think I missed any steps in the example docs.

**Comment by JSteunou** [comment] 2015-05-11 08:54
same error, `npm install handlebars` solved it.

I have not yet inspect the code to find the root cause, also this error seems weird because this example uses rendr-handlebars and handlebars directly...

**Comment by liamfd** [comment] 2015-05-14 16:46
@JSteunou does the `npm install handlebars` also get it working on the client? Even when I do that I'm getting the `Uncaught Error: Cannot find module 'handlebars' ` in the browser console and it doesnt appear to be instantiating the backbone apps.

**Comment by JSteunou** [comment] 2015-05-14 18:25
yes, it did.

**Comment by crwang** [comment] 2015-05-15 03:14
@liamfd make sure you change the browserify as well:

https://github.com/ingiulio/rendr-examples/blob/addHandlebarsDep/00_simple/Gruntfile.js#l70

**Comment by ingiulio** [comment] 2015-05-15 05:12
Hey @liamfd sorry I just saw this. This PR fixes the problem: https://github.com/rendrjs/rendr-examples/pull/20
Sorry this is my bad, I forgot to update the examples repo right after I made a PR on Rendr.
@saponifi3d can the PR be merged or do you have any concern about it? 
Thanks!

**Comment by crwang** [comment] 2015-08-20 14:50
Closing this as the PR has been merged.

**Closed by crwang** 2015-08-20 14:50 UTC
